### PR TITLE
Modify logic for V7 variant

### PR DESCRIPTION
**Pull request by 2acoin**
Modified the code in the extensions\cryptonight-v7.json file to correct the logic for activation of V7.

### CODE REVIEW

**Comment by kennetanti** [comment]
This pull request look gross. I dont think u should check for last_block == 0 ... You should just set it to UINT32_MAX if you want it to be "v7 forever"

**Comment by pmitchev** [comment]
I use this logic in other files. The default is 0 and it actually makes sense. It can never be 0.
Thank you @2acoin

**Comment by kennetanti** [comment]
But block index and last block default to 0. I would argue if its 0 that means its unconfigured and they dont want cryptonight v7. Mainly because then the multiply code could be identical (almost) where if block index and last block are not specified in the config, then the blockchain would not use v7

**Comment by kennetanti** [comment]
Otherwise you would need 2 different builds for v0 vs v7 because there is no other value you can use to disable v7 ? Idk your the master of the repo i guess. (If i really cared that much i would make forkforknote)

**Comment by pmitchev** [comment]
You are right, it should be more clear _BLOCK_INDEX should never be 0 for new coins

**Comment by kennetanti** [comment]
That way you wouldnt have to change your config files to work with forknote-pool or forknoted if they are designed for cryptonote-generator and vice-versa. Getting some liquor then ill do the thing

**Comment by kennetanti** [comment]
#84 looks like this will work with /multiply/ jsons if you leave them both on default of 0.  Or two identical numbers. Because 0 <= x < 0 is always false

**Pull request merged**
