### PR TITLE
Add mnemonic support extension to simplewallet

### PR DESCRIPTION
**Pull request by ZedPea**
Heya,

Recently we added mnemonics to Turtlecoin, and we thought you guys might like to have the option to add it as an extension. You can see the more readable version of the changes here - https://github.com/turtlecoin/turtlecoin/commit/347576be3281f3e42bb03de100439b9f31cfb5fe

I'm managed to get it to compile with some difficulty - it seemed that even without any changes the code didn't really want to compile on my gcc version, some hopefully this will work fine on your machines. I have tested out the mnemonic seeds and they export and import correctly.

Let me know if you want to clarify anything or need anything fixed up.

Thanks!

### CODE REVIEW

**Comment by frango9000** [comment]
hello, nice addition, ty
just to point out, mnemonics.json conflicts with bug-fixes.json 
both try to do the same change:
`
        {
          "action": "replace",
          "marker": "return sizeof(rs_comm) + pubs_count * sizeof(rs_comm().ab[0]);",
          "parameters": {
            "text": [
              "     return sizeof(rs_comm) + pubs_count * sizeof(ec_point_pair);"
            ]
          }
        },
`

**Comment by pmitchev** [comment]
Yes, bug fixes fir the Core should be placed in **bug-fixes.json**

**Comment by pmitchev** [comment]
Fixed here:
https://github.com/forknote/cryptonote-generator/commit/749c73146b0d0363802bfd32a85753d19b668b9a

**Comment by ZedPea** [comment]
Thanks guys, sorry about that. I wasn't sure if I was doing something stupid on my end because it wasn't compiling without those fixes.

**Comment by pmitchev** [comment]
Thank you for your contribution. It will be included in the next Forknote version

**Pull request merged**
